name and iconography change from ninja to stars
redhat-cop/ninja-board pull request #131
Opened 2021-01-18 16:47 UTC by matallen

2021-01-20 02:04 UTC, sabre1041 requested changes
Small changes. Otherwise good

2021-01-20 02:04 UTC, sabre1041 commented on src/main/webapp/mojo/mojo-dashboard-card.jsp
> +						//document.getElementsByClassName("_level")[0].src=ctx+"/../../images/"+value.toLowerCase()+"_belt_icon.png";
Remove the comments?

2021-01-20 15:02 UTC, matallen commented on src/main/webapp/mojo/mojo-dashboard-card.jsp
> +	return "ablock";
wow, thanks for spotting that - you were my test case today!

2021-01-20 23:22 UTC, matallen commented on src/main/webapp/mojo/mojo-dashboard-card.jsp
> +						//document.getElementsByClassName("_level")[0].src=ctx+"/../../images/"+value.toLowerCase()+"_belt_icon.png";
removed

2021-01-20 23:23 UTC, matallen commented on src/main/webapp/mojo/mojo-dashboard-card.jsp
> +	return "ablock";
this has been removed in the commit below

2021-01-21 04:26 UTC, sabre1041 approved these changes
LGTM

2021-01-21 04:27 UTC, merged